### ISSUE TITLE
Add new Azure IoT Hub TLS certificate

### ISSUE THREAD

**Issue by Andy928483** [mongoose-os-libs/ca-bundle#5]
According to https://techcommunity.microsoft.com/t5/internet-of-things-blog/azure-iot-tls-critical-changes-are-almost-here-and-why-you/ba-p/2393169 Azure IoT Hub requires a new certificate for TLS connections.

We could update the ca.pem ourselves, but I think it would be good to add it to the default ca.pem. Especially new users will run into problems, when they start using mongoose OS with Azure IoT Hub and the certificate is missing.

**Comment by rojer** [comment]
sounds good, please send a PR

**Comment by Andy928483** [comment]
We are currently testing the new ca.pem with the test Azure IoT Hub (g2cert.azure-devices.net). I will create the PR as soon as we are done with ours tests.

**Comment by Andy928483** [comment]
I updated the ca.pem and tested it with the test Azure IoT Hub g2cert.azure-devices.net. I created a pull request with the new ca.pem.

**Comment by rojer** [comment]
merged https://github.com/mongoose-os-libs/ca-bundle/pull/6, thank you!
